# Choose one of: "serial" (Classic SPP via /dev/rfcommX) or "ble"
transport:
  type: serial
  # For serial:
  port: /dev/rfcomm0
  baudrate: 38400
  timeout_s: 2.0
  # For BLE (if type: ble):
  ble_mac: "00:10:CC:4F:36:03"
  # Common:
  retries: 3

# Polling
poll:
  interval_ms: 250
  pids: ["0C","0D","05","0F","10","2F","11","04","0B","2F","06","07","1F","31","33"]
  discover_supported: true   # probe PID maps at startup


# Logging
logging:
  csv_path: /home/apella/dirty-obd/obd_logs/data.csv
  sqlite_path: /home/apella/dirty-obd/obd_logs/data.sqlite
  rotate_csv_daily: true

# Web
web:
  host: 0.0.0.0
  port: 8080

dtc_profiles:
  path: /home/apella/dirty-obd/data/   
  default_profile: Default             # initial profile
  state_path: ./state/vehicle_profile.json  # persists the last selection
